### ISSUE TITLE
Add: The Chan Zuckerberg Initiative

### ISSUE THREAD

**Issue by fvcproductions** [fvcproductions/apprenticeships.me#101]
## Company

The Chan Zuckerberg Initiative

## Description

The Chan Zuckerberg Initiative is using technology to help solve some of our toughest challenges — from preventing and eradicating disease, to improving learning experiences for kids, to reforming the criminal justice system. Founded by Priscilla Chan and Mark Zuckerberg in 2015, CZI’s mission is to build a more inclusive, just, and healthy future for everyone.

## Link

https://chanzuckerberg.com/join-us/openings/

## Location

- San Francisco, CA

## Featured Image

![czi (1)](https://user-images.githubusercontent.com/4284691/56452691-f393df80-62e8-11e9-91ad-61b3d68e7f73.jpg)

---

> By submitting this issue, I have verified the following ✅

- [x] Checked to see if the apprenticeship has already been added before 🤔️
- [x] Made sure all the details were provided 🔍️

**Comment by fvcproductions** [comment]
@benjaminmodayil Going to work on adding this one in and then a few tweaks so that every apprenticeship has a location - I will then post on PH early tomorrow. Sound cool?

**Comment by benjaminmodayil** [comment]
Sounds good. I'll be on the lookout for any PRs then. 

I saw your note about next Monday on the form PR. I'm good with either date you set.
