### ISSUE TITLE
Feature Request: Add PH Badge

### ISSUE THREAD

**Issue by fvcproductions** [fvcproductions/apprenticeships.me#118]
## Is your feature request related to a problem? Please describe.

Yes, we want more PH upvotes 😂 

## Describe the solution you'd like

https://www.producthunt.com/posts/apprenticeships-me/embed

```
<a href="https://www.producthunt.com/posts/apprenticeships-me?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-apprenticeships-me" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=153013&theme=light" alt="Apprenticeships.me - Find a new career learning from the industry itself. | Product Hunt Embed" style="width: 250px; height: 54px;" width="250px" height="54px" /></a>
```

## Describe alternatives you've considered

N/A

## Additional context

I think this can go in the second hero after the text? cc @benjaminmodayil

**Comment by benjaminmodayil** [comment]
The second hero feels really out of place. What if it were in the navigation with the Visit on Github + Contribute buttons?
