### ISSUE TITLE
Bug: Metadata image shows first apprenticeship versus one about the site

### ISSUE THREAD

**Issue by benjaminmodayil** [fvcproductions/apprenticeships.me#122]
## Describe the bug

The metadata thumbnail shows the first apprenticeship versus one about the site.

## To Reproduce

Paste the link on Facebook.

## Additional context
https://i.imgur.com/9vPEQI9.png

**Comment by benjaminmodayil** [comment]
A possible solution would to set one up with one of these as a template:
https://drive.google.com/open?id=1QWs32o73UrBLH175QBDtmGRQjwLq-nJB

**Comment by fvcproductions** [comment]
Huh - weird - our meta tags should already be configured to have that one banner as the featured image.

Check https://metatags.io/ - it shows correct banner

**Comment by fvcproductions** [comment]
Oh now I see image: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fapprenticeships.me

**Comment by fvcproductions** [comment]
@benjaminmodayil yeah ur right lol

https://developers.facebook.com/tools/debug/og/object/?q=https%3A%2F%2Fapprenticeships.me%2F

**Comment by fvcproductions** [comment]
@benjaminmodayil Just a heads up I won't have as much bandwidth to work on this so let's try to get someone from the community to!

**Comment by benjaminmodayil** [comment]
I think this issue can be closed now.

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fapprenticeships.me

Seems we have the correct meta image for sharing now.
