### ISSUE TITLE
Bug: All heading styles aren't being applied

### ISSUE THREAD

**Issue by benjaminmodayil** [fvcproductions/apprenticeships.me#132]
## Describe the bug
All of our headings aren't retaining their font-weights and font-sizes. I'm not entirely sure, but it might be due to a dependency update to the site. Possibly one relating to PostCSS or Tailwind. I think I saw an email about one of these.

**Comment by benjaminmodayil** [comment]
@fvcproductions This is now fixed. It seems we never labeled font-sizes and etc explicitly to the headings.

The reason they all got small was because a CDN'd version of Tailwind was included in the head of the site somewhere in the past. This forced an automatic V.1 update onto our site and included an updated version of Normalize.css via the Tailwind CDN that added "display: block" to images by default, normalized all our headings to the same size, and etc. The CDN was removed as it shouldn't have been included in the first place.

**Comment by fvcproductions** [comment]
fixed in #134
