### ISSUE TITLE
Bug: Images don't show up anymore

### ISSUE THREAD

**Issue by fvcproductions** [fvcproductions/apprenticeships.me#133]
## Describe the bug

Looks like JS/CSS is off and the card component has images that don't show up anymore along with the tags.

## Expected behavior

CSS should display components properly and images should load.

## Screenshots

![Screen Shot 2019-05-27 at 7 37 07 PM](https://user-images.githubusercontent.com/4284691/58442219-0acba700-80b7-11e9-9273-555327f62602.jpg)

## Additional context

I might consider switching to Bulma instead of Tailwind.

**Comment by benjaminmodayil** [comment]
@fvcproductions I ran NPM build locally and it updated the images. The paths got messed up. There's an error in the script for assigning the correct minified paths but I couldn't find the exact issue. This isn't a Tailwind problem, look at #134 and #132 for clarification on the styling issues.

**Comment by fvcproductions** [comment]
@benjaminmodayil This issue has been resolved - thanks again for the fix!

**Comment by benjaminmodayil** [comment]
@fvcproductions Apparently the fix didn't take. I've reset it so the images are back up for now, but I'll need a deeper look into why the images keep getting messed up. I thought my previous "fix" would work, but I guess not.

**Comment by dpikt** [comment]
Images are not visible presently on the site. There's something up with the image paths script where it's setting the hash to `undefined`. That's as far as I could get, it's tough to debug because it works fine locally.

**Comment by benjaminmodayil** [comment]
@dpikt Appreciate the help! Yeah, I'll look at this tonight. The latest build broke it.

The issue lies in the `correct-image-paths.js` file. Something here is off, but I haven't had time to diagnose it.

I have a temporary fix whenever this happens to update the image paths on Algolia, but requires the Algolia key I have on my home computer. At work at the moment, so I can't help fix it until evening.

**Comment by benjaminmodayil** [comment]
Fixed... for now. Just ran "npm run build" and it updated Algolia.

Still needs a deeper look into the script in my last message.

**Comment by fvcproductions** [comment]
Looks like there was a regression again @benjaminmodayil 🤔 

Might be worth exploring a different model of filtering but it may also be related to Netlify settings?

![Screen Shot 2019-07-30 at 9 28 24 PM](https://user-images.githubusercontent.com/4284691/62184662-dd4be580-b313-11e9-8575-3acc99b5b160.jpg)

**Comment by benjaminmodayil** [comment]
@fvcproductions Yeah, sorry this is still happening. If it ever goes down again, just re-deploy the site in the Netlify dashboard.

Looking at it deeper around lunch time today.

**Comment by fvcproductions** [comment]
@benjaminmodayil I went ahead and created a Zapier task that will automatically build this site every day at midnight Pacific Time - so this shouldn't be an issue at least in that aspect anymore 👍🏽

**Comment by benjaminmodayil** [comment]
Hmmm. I don't think that will solve the issue. It sounds like that every few days it will generate the page with an error.

**Comment by fvcproductions** [comment]
Aww bummer
