### ISSUE TITLE
Add: NYC Technology Fellowship Program

### ISSUE THREAD

**Issue by benjaminmodayil** [fvcproductions/apprenticeships.me#143]
## Company

NYC Technology Fellowship Program

## Description

We are currently recruiting candidates to apply for the Spotify New York City Technology Fellowship Program -- a development program aimed at hiring engineers just entering the professional tech environment from a diverse set of backgrounds.

Participants in the fellowship program will operate as a team within Spotify for 18 weeks while receiving mentoring, personal & professional development from a broad set of employees to help them reach their full potential and learn what it’s like to work at Spotify. 

The 2019 New York City Technology Fellowship Program will admit candidates for backend and frontend roles.

## Link

https://ttp.nyc/spotify-fellowship-2019

## Location

New York City

*This entry was submitted by the form on the site*

**Comment by fulin426** [comment]
current link is outdated for 2019

**Comment by benjaminmodayil** [comment]
@fulin426 Thanks! I'll check this out tonight.

@fvcproductions Glad to know our form submission is working properly.

**Comment by fvcproductions** [comment]
Link has been updated 👍🏽
