### ISSUE TITLE
Add: LaunchPad Lab

### ISSUE THREAD

**Issue by benjaminmodayil** [fvcproductions/apprenticeships.me#164]
## Company

LaunchPad Lab

## Description

LaunchPad Lab is a web development studio focused on growing businesses. We are highly skilled and focused on success. We design with reason, impress users with the best web experience, and write exceptional code. We measure ourselves by the success of our clients.

## Link

https://launchpadlab.com/careers/

## Location

Chicago, IL

*This entry was submitted by the form on the site*

**Comment by bhennes2** [comment]
Please include this link in our description as well: https://launchpadlab.com/blog/apprenticeships-how-we-approach-this-old-new-trend/

Thanks!

**Comment by dpikt** [comment]
Bump :)

**Comment by dpikt** [comment]
Or is this resolved?

**Comment by benjaminmodayil** [comment]
I believe it has not been resolved. I'll take a look at adding this tonight :) I've been wanting to update some stylings anyway.

**Comment by fvcproductions** [comment]
Any update on this?
