### ISSUE TITLE
Add: Quora Software Engineer Apprenticeship

### ISSUE THREAD

**Issue by fvcproductions** [fvcproductions/apprenticeships.me#172]
## Company

Quora

## Description

Quora’s Software Engineering Apprentice Program is a 6-month paid opportunity for passionate, aspiring software engineers from a non-traditional background to gain the knowledge, tools, and skills to thrive as a software engineer.

## Link

https://www.quora.com/careers

## Location

- Mountain View, CA

## Featured Image

Include a link to an image to feature with the apprenticeship that is at least 500px by 500px or upload it directly here. Also, please view the contributing guidelines to learn what makes an acceptable featured image.

![image](https://cdn.vox-cdn.com/thumbor/XZOiMSnjfLxakH367c7Og-Bb6v4=/7x0:633x417/1200x800/filters:focal(7x0:633x417)/cdn.vox-cdn.com/assets/1296846/quoralogo.jpg)

## More info

Software Engineer Apprentice

MOUNTAIN VIEW, CAUNIVERSITYCONTRACT

Quora's mission is to share and grow the world's knowledge. We're building a platform that allows anyone to get the best answer to any question. As a team, we are dedicated to holding high standards, developing a strong and passionate culture, and emphasizing impact.

Quora’s Software Engineering Apprentice Program is a 6-month paid opportunity for passionate, aspiring software engineers from a non-traditional background to gain the knowledge, tools, and skills to thrive as a software engineer.

In your role as an apprentice, you’ll take on important projects that help drive the company and product forward. We believe that high impact projects are the best way to grow and develop your skills. You may work in areas such as:

- Mobile: mobile apps are our most important platforms for user engagement! Work with designers and data scientists to build smooth mobile app product interactions that are performant and reliable for great daily use.
- Frontend Platform: enable productivity and innovation of our frontend developers, through building frontend tools, building blocks, and frameworks to power the Quora product on all platforms — web, mobile web, iOS, and Android. We are currently modernizing our frontend stack!
- Core Product: build out and scale user-facing product features to drive engagement and help the product grow.

We believe in mentorship that will accelerate your growth and help you develop strong engineering practices. Throughout the apprenticeship, you will work closely with your mentor and the rest of your team. You’ll receive feedback through coaching, code reviews, and one on one meetings; and broaden your learning through engineering tech talks, reading groups, and our culture of awareness. The program includes a mid-point formal evaluation of your progress. At the end of the program, based on your progress, we will consider you for a full-time Software Engineer role.

Responsibilities:
Work with a team on projects important to the company and its goals
Write well-crafted, well-tested, readable, maintainable code
Participate in code reviews, gaining knowledge from other engineers and spreading some of your own
Develop strong engineering practices

Minimum Qualifications:
Completion of a coding bootcamp
Have made and worked on large scale coding projects, including work that you may have done during a bootcamp experience or on your own
Experience working with either a web application framework, or with iOS or Android app development
Strong communication and inter-personal skills
Love of learning, mentorship, and improving everyone around you
Love of the Quora product

---

> By submitting this issue, I have verified the following ✅

- [x] Checked to see if the apprenticeship has already been added before 🤔️
- [x] Made sure all the details were provided 🔍️

**Comment by benjaminmodayil** [comment]
Is this still open @fvcproductions seems you already added it.

**Comment by benjaminmodayil** [comment]
This has already been added to the site. Closing for now.

**Comment by fvcproductions** [comment]
Yep, it was added - thanks for closing!
