### ISSUE TITLE
Add: Quora Apprenticeshop

### ISSUE THREAD

**Issue by jackieore** [fvcproductions/apprenticeships.me#173]
## Company

Quora

## Description

Quora's mission is to share and grow the world's knowledge. We're building a platform that allows anyone to get the best answer to any question. As a team, we are dedicated to holding high standards, developing a strong and passionate culture, and emphasizing impact.

## Link

https://jobs.lever.co/quora/19c6eb11-22f1-4815-8382-0e78e70a6ddd

## Location

- Mountain View, CA

## Featured Image

https://cdn.vox-cdn.com/thumbor/XZOiMSnjfLxakH367c7Og-Bb6v4=/7x0:633x417/1200x800/filters:focal(7x0:633x417)/cdn.vox-cdn.com/assets/1296846/quoralogo.jpg

Include a link to an image to feature with the apprenticeship that is at least 500px by 500px or upload it directly here. Also, please view the contributing guidelines to learn what makes an acceptable featured image.

---

> By submitting this issue, I have verified the following ✅

- [] Checked to see if the apprenticeship has already been added before 🤔️
- [] Made sure all the details were provided 🔍️

**Comment by benjaminmodayil** [comment]
Hi @jackieore that link currently leads to nowhere. Do you have another?

**Comment by benjaminmodayil** [comment]
Also, there seems to be another listing for Quora currently, does that fit your needs, or do you think that one should be updated with different information?

**Comment by jackieore** [comment]
Good morning! We can remove my submission. I realized after sending it in that it was already listed a few pages in. Sorry for any hassle I might have created! 

Best,
Jackie

**Comment by benjaminmodayil** [comment]
Sounds good! Thanks for the reply.
