### ISSUE TITLE
Add: Airbnb

### ISSUE THREAD

**Issue by julinvictus** [fvcproductions/apprenticeships.me#188]
## Company

Airbnb

## Description

What is the Connect Apprenticeship Program? 
The Connect Program is a paid 6-month program to provide a pathway to our entry-level software engineering roles for individuals with nontraditional technical backgrounds.

## Link

https://careers.airbnb.com/positions/1879075/

## Location

- San Francisco, CA

## Featured Image

<img width="375" alt="AIRBNB" src="https://user-images.githubusercontent.com/50844569/66275248-8d216000-e83b-11e9-9b68-6dbf3d6cf1a9.png">

---

> By submitting this issue, I have verified the following ✅

- [x] Checked to see if the apprenticeship has already been added before 🤔️
- [x] Made sure all the details were provided 🔍️

**Comment by benjaminmodayil** [comment]
@julinvictus  Do you have an updated link for this? Seems to be outdated already.

**Comment by julinvictus** [comment]
It seems application ended on Oct 19 so they put offline. Would it be interesting to have this link? https://www.techhireoakland.org/apprenticeships/airbnb

**Comment by benjaminmodayil** [comment]
@julinvictus  Hmm I'm not sure. Usually the links should be direct links. Thoughts @fvcproductions  ?

**Comment by fvcproductions** [comment]
hmmm i think it would still be worth putting any link just so it's known that airbnb does have an apprenticeship program (i had no idea!)
