### ISSUE TITLE
Bug: Urban Technology Project - Page not found

### ISSUE THREAD

**Issue by BinuDavid** [fvcproductions/apprenticeships.me#201]
## Describe the bug
Unable to located page when link is clicked

## To Reproduce

1. Go to 'apprenticeships.me'
2. Click on 'search input and enter "phil" and you will see Urban Technology Project listed'
3. Select "Urban Technology Project"
4. See error - Page Not Found

## Expected behavior
Page Found

## Desktop (if applicable)

- OS: Windows
- Browser Firefox Browser
- Version 70.0.1

**Comment by benjaminmodayil** [comment]
Thanks @BinuDavid! I'll check this out tomorrow.

**Comment by benjaminmodayil** [comment]
Also, for anyone that wants to do this before I get to it... https://utp-philly.org/digital-service-fellows/ seems to be a good link for now.
