### ISSUE TITLE
Add: Apprenticeships at Barclays

### ISSUE THREAD

**Issue by benjaminmodayil** [fvcproductions/apprenticeships.me#204]
## Company

Apprenticeships at Barclays

## Description

Barclays offers a variety of apprenticeships in the UK from tech to ops.

## Link

https://joinus.barclays/eme/apprenticeships/

## Location

UK

*This entry was submitted by the form on the site*

**Comment by aaronclarkcodes** [comment]
complete when #217 is approved/merged

**Comment by benjaminmodayil** [comment]
Closing. Thanks @aaronclarkcodes !
