### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by kaichunwu** [fvcproductions/apprenticeships.me#220]
## Company

No current.

## Description

No current.

## Link

https://www1.coe.neu.edu/~wukaichun

## Location

- San Francisco, CA
- Seattle, WA

## Featured Image

Include a link to an image to feature with the apprenticeship that is at least 500px by 500px or upload it directly here. Also, please view the contributing guidelines to learn what makes an acceptable featured image.

---

> By submitting this issue, I have verified the following ✅

- [] Checked to see if the apprenticeship has already been added before 🤔️
- [] Made sure all the details were provided 🔍️

**Comment by benjaminmodayil** [comment]
Hi @kaichunwu  I'm going to close this issue. The site you submitted doesn't appear to be an apprenticeship program, but a portfolio. We don't have any plans at the moment for portfolios, but it does give me thoughts for the future!
