### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by kassablanka** [fvcproductions/apprenticeships.me#239]
## Company

XYZ

## Description

XYZ is a company that does ABC.

## Link

https://xyz.com

## Location

- San Francisco, CA
- Chicago, IL

## Featured Image

Include a link to an image to feature with the apprenticeship that is at least 500px by 500px or upload it directly here. Also, please view the contributing guidelines to learn what makes an acceptable featured image.

---

> By submitting this issue, I have verified the following ✅

- [] Checked to see if the apprenticeship has already been added before 🤔️
- [] Made sure all the details were provided 🔍️

**Comment by fvcproductions** [comment]
Closing - not relevant
