### ISSUE TITLE
Add: React Native Developer

### ISSUE THREAD

**Issue by benjaminmodayil** [fvcproductions/apprenticeships.me#246]
## Company

React Native Developer

## Description

We are looking for someone who has experience with React Native, knowledge of API's, and Bluetooth to join our team. We are building 2 distinct platforms aimed at helping brick & mortar businesses and communities survive and thrive through the COVID pandemic.

Regulr:   www.regulr.io
Distance: www.distance.regulr.io

Contact us at contactus@regulr.io if you are interested. Thanks!

## Link

www.regulr.io

## Location

Virtual

*This entry was submitted by the form on the site*

**Comment by fvcproductions** [comment]
Not an apprenticeship, I will close
