### ISSUE TITLE
Add featured image guidelines to CONTRIBUTING doc

### ISSUE THREAD

**Issue by fvcproductions** [fvcproductions/apprenticeships.me#42]
Bringing in convo from #41 

I can imagine some people submitting a logo and others submitting a picture of the building or interior office. This could get messy if not specified and people submit varying types of images.

Personally, I like the idea of an image like ones lower in the page for Viget (https://www.viget.com/careers/). Kind of a candid interior office shot.

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to see if the issue has already been discussed before 🤔️
- [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by fvcproductions** [comment]
@benjaminmodayil By the office images, you mean like this, right?

![Image](https://static.viget.com/careers/_540xAUTO_crop_center-center/Durham-entry.jpg)

**Comment by fvcproductions** [comment]
I like the idea of having the candid office shot as long as the logo is showing and the people are harder to see or not present in the shot. 

I don't want faces to be associated with the company since that might dissuade people to apply or look into the company due to unconscious biases.

**Comment by benjaminmodayil** [comment]
Yeah. I think that image you pulled works great for the thumbnails.

👍on the note about showing faces.

I'll write up an edit to the guideline and submit a PR tonight.

**Comment by fvcproductions** [comment]
This was actually tackled already so I just need to update the guidelines for developers.
