### ISSUE TITLE
Bug: API rate limit for GitHub contributors

### ISSUE THREAD

**Issue by fvcproductions** [fvcproductions/apprenticeships.me#43]
## Describe the bug

```
{
  "message": "API rate limit exceeded for {MY IP}. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

## To Reproduce

1. Go to https://apprenticeships.me/ a crap ton
2. Contributors from GitHub don't show up

## Expected behavior

Auth for API so there's never any rate limit reached

## Screenshots

<img width="1560" alt="screen shot 2019-01-14 at 4 00 26 pm" src="https://user-images.githubusercontent.com/4284691/51149123-95e98600-1815-11e9-836f-9b6661d60327.png">

## Additional Context

https://developer.github.com/v3/#rate-limiting

**Comment by benjaminmodayil** [comment]
Yeah I ran into this locally when initially working on the Github portion. Is there a way for Hugo to fetch API data and build items statically?

I know in GatsbyJS (another static site generator) you can hit and pull data from an API during the build process, but I wasn't sure if Hugo could as well. This could be another route to avoid multiple requests if we fetch the data we need and build it statically. It probably would be easier to do Auth though... albeit probably more fun doing it with Hugo if possible 😄

**Comment by fvcproductions** [comment]
@benjaminmodayil Apologies for the delay here, I'm not entirely sure but some sleuthing into Hugo's docs would probably be better. Gatsby is much newer than Hugo and has a smaller community so I'd reckon Hugo can do this as well.

**Comment by benjaminmodayil** [comment]
@fvcproductions I'll look into this. I always thought Hugo had a smaller community than Gatsby, haha. But I guess that's just because I use Gatsby a lot...
