### ISSUE TITLE
Feature Request: Bring back apprenticeships in README

### ISSUE THREAD

**Issue by fvcproductions** [fvcproductions/apprenticeships.me#65]
## Is your feature request related to a problem? Please describe.

Ever since we moved the apprenticeships to a website, it feels like we've been getting less traction.

## Describe the solution you'd like

Apprenticeships listed back in the README with better documentation on how to get an apprenticeship added. 

I would like to get same traction as https://github.com/poteto/hiring-without-whiteboards

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by benjaminmodayil** [comment]
Hi @fvcproductions 

Previously I used a node script that took the items in the original README to parse them into separate `.md` files. I just checked that node script and I was able to quickly convert them back into single file with the correct formatting.

I think there would be room for error if a contributor had to update the README and the separate `apprenticeships/` folder with another `.md` file. This leads me to think we need some automation added:

(Option 1) I think we could have a small script that run every time a new separate apprenticeship `.md` file was added to the `/apprenticeships/` folder and then it would generate an updated README with the listing of apprenticeships there or (Option 2) have a script read the updated README and update the separate apprenticeship `.md` files. The script would run in conjunction with Netlify when the repository is updated.

I believe both options would require us to "tag" a specific part the README with two HTML comments `<!-- apprenticeships -->` in order for either scripts to run properly.

Let me know your thoughts on pursuing this.

**Comment by fvcproductions** [comment]
@benjaminmodayil After giving it some thought, I think we should leave it as is for now and just continue to make the website more useful and amazing.

I often see what you just described in one form or another, e.g.

https://flawlessapp.io/designtools with https://github.com/LisaDziuba/Awesome-Design-Tools

everything here lol: https://github.com/sindresorhus/awesome

the link I mentioned earlier except it doesn't even have a website - it uses airtable: https://github.com/poteto/hiring-without-whiteboards

Anyways, I think we should be creating a website not a nice Markdown file here. 

Our end result is something like https://confs.tech/ which ties to https://github.com/tech-conferences/confs.tech and making it even nicer looking and easier to contribute to down the road as there are more apprenticeships added out there in the wild.
