### ISSUE TITLE
Feature Request: Add website to Product Hunt

### ISSUE THREAD

**Issue by fvcproductions** [fvcproductions/apprenticeships.me#74]
## Is your feature request related to a problem? Please describe.

Need more apprenticeships added; more visibility would be great

## Describe the solution you'd like

First, we need to add images and update our contributing guidelines

Ideally too, we can add a banner welcoming new PH viewers but not really necessary

Only then should we get apprenticeships.me added to PH

https://www.producthunt.com/posts/new

## Describe alternatives you've considered

Are there other places we can share to?

## Additional context

Would love additional insight on this idea from @benjaminmodayil

**Comment by benjaminmodayil** [comment]
I think getting this site on Product Hunt is a great idea! Let me work on some notes tonight on my thoughts about this. I'll send another reply here with any other ideas before PH.

What were you thinking in relation to a banner? I'll help with accumulating thumbnails (is this what you meant by images?).

As to other places for sharing, I'll try to think of more places. I feel like we could target some specific tech related reddits + forums and point them to the PH post. This could help gain traction towards it. Another idea would be posting the PH link on Twitter, but in a threaded reply we could tag specific apprenticeships on the site in hopes they might retweet.

I'll add more here in the morning once I've gone through everything. I just recently started a new job so I'm a little scattered at the moment. 😆

**Comment by fvcproductions** [comment]
You've already provided some great insight - thanks @benjaminmodayil! 👍 

Congrats on the new job 🎉 

## Images

So yes images would be nice to have for the apprenticeships to have a little more going on. I think just a logomark is good for now, I know we discussed office spaces before but having a logo image makes more sense. Ideally, we have something like this for every apprenticeship before sharing on PH:

![do](https://urbankenyans.com/wp-content/uploads/2018/01/digitalocean-logo.jpg)

## Banner

For the banner on the website, it would just be something like "Hey! Welcome to apprenticeships.me Product Hunters - feel free to contribute an apprenticeship here" and then that would like to a new apprenticeship issue on GitHub. 

We could also create a config that would take a form from the website and just create an issue on GitHub so it's more accessible to those outside of tech but that's not a blocker.

## Sharing Channels

In addition to sharing this on PH, we also want to think about what our strategy will be in sharing this on other channels. Here's where I'm thinking of posting the website/PH link once it's published on Product Hunt

- Slack workspaces I'm a part of (Slack's Slack, Techqueria, Women Who Code, Women TechMakers, Write/Speak/Code)
- Hacker News
- my personal LinkedIn, Twitter, Instagram, Reddit & Facebook

**Comment by benjaminmodayil** [comment]
So in terms of images for each post, it probably would be good to favor the office photo versus the logo mark since the title for the company is already below where the thumbnail will probably be and most logo marks tend to include the company title... but logo marks are easier to come by than office photos, so let's go with the logo-marks.

An idea would be to add another front-matter variable for an office photo. If a user hovers over a card, we could swap out the logo mark for an office photo.

I've seen people create banners for Product Hunt visitors before. Is there some sort of template that people tend to use? Or should we just create it from scratch?

+100 on the form. I can take a look at how that might work. The only thing is that people submitting via the form might not get contributor status at the bottom of the page unless they sign into Github itself and submit an issue there.

I'll take a look at the different Slacks/Discords that I can share. I'll share on my social media as well.

It would be good to get through the remaining issues for the repository before submitting to PH. I might try tackling quite a few of these tomorrow morning. I've been looking for a reason to Twitch stream code once again.

**Comment by fvcproductions** [comment]
Agreed we should go through remaining issues and tackle those first before anything else. 

+1 on logo photos

I can look into banner templates for PH.

For the form submission, I think it's okay if they don't get recognition since they're just submitting a form at the end of the day 😂 

Let's target an April 15th release/all-out visibility squad announcement 📢

**Comment by fvcproductions** [comment]
@benjaminmodayil FYI I sent u an invite on PH for the upcoming site

https://www.producthunt.com/upcoming/apprenticeships-me

**Comment by benjaminmodayil** [comment]
@fvcproductions 

Got it! Working on the form as we speak.

Did you happen to look into PH banners?

**Comment by fvcproductions** [comment]
@benjaminmodayil No it didn't seem to make sense - the only CTA we have the website is really contributing to our directory and clicking on apprenticeship opportunities. 🤔

**Comment by benjaminmodayil** [comment]
Also apologies for any emails related to created issues... I'm experimenting with what permissions are actually required by the github API for POST requests.

**Comment by fvcproductions** [comment]
@benjaminmodayil Oh that makes sense - no worries! Carry on 👍

**Comment by benjaminmodayil** [comment]
https://drive.google.com/open?id=1QWs32o73UrBLH175QBDtmGRQjwLq-nJB

@fvcproductions Not sure if you'd like to use these, but thought these might be nice to share through social media instead of just a link.

The template file is included if you wanted to edit them.

**Comment by fvcproductions** [comment]
Heads up on this: https://github.com/fvcproductions/apprenticeships.me/pull/96#issuecomment-483789729

**Comment by fvcproductions** [comment]
I love the images - agree it would be better to use those! Also, I noticed some products have GIFs now but idk what ours would look like so I think just a static image is fine.

**Comment by fvcproductions** [comment]
## Launch on PH Strategy

- Feature on Upcoming https://www.producthunt.com/upcoming/apprenticeships-me
- Add ability for non-technical users to contribute through a form that creates a GitHub issue
- Add post to PH https://www.producthunt.com/posts/new
- Share to Slack workspaces, Hacker News, LinkedIn, Twitter, Instagram, Reddit, Facebook, Snapchat, etc.

**Comment by benjaminmodayil** [comment]
Just checking on how we share. Are we sharing now with the upcoming link for Product Hunt, when it launches, or both?

**Comment by fvcproductions** [comment]
@benjaminmodayil I was thinking we just share after it's launched on PH

**Comment by fvcproductions** [comment]
@benjaminmodayil Looks like I got too busy this morning so I'm going to push the launch date to tomorrow morning - May 1st 👍  

But basically the plan is:

1) Post on PH on Wed May 1st at 9 AM Pacific Time or 12 PM Eastern Time

2) @fvcproductions shares on relevant channels and ask for upvotes and shares

- [ ] Slack Workspace - Techqueria
- [ ] Slack Workspace - Women Who Code
- [ ] Slack Workspace - Women Techmakers
- [ ] Slack Workspace - Write/Speak/Code
- [ ] Slack Workspace - Latinas in Tech
- [ ] Slack Workspace - Slack
- [ ] [Hacker News](https://news.ycombinator.com/user?id=fvcproductions)
- [ ] [LinkedIn](https://www.linkedin.com/in/fvcproductions/)
- [ ] [Twitter](https://twitter.com/fvcproductions)
- [ ] [Instagram](https://www.instagram.com/fvcproductions/)
- [ ] [Reddit](https://www.reddit.com/user/fvcproductions)
- [ ] [Facebook](https://www.facebook.com/fvcproductions2013)
- [ ] Short Blog Post - [Medium](https://medium.com/@fvcproductions), [LinkedIn Posts](https://www.linkedin.com/in/fvcproductions/), [Personal Website](https://www.fvcproductions.com/)

3) @benjaminmodayil shares on relevant channels and ask for upvotes and shares

- [ ] Slack Workspaces
- [ ] Hacker News
- [ ] LinkedIn
- [ ] Twitter
- [ ] Instagram
- [ ] Reddit
- [ ] Facebook
- [ ] Snapchat

4) Post Launch, let's share all the links in this issue and we can both reshare, retweet, upvote, like, etc. each other's links before closing it

5) Celebrate 🎉

**Comment by benjaminmodayil** [comment]
Looks good! Might be a last minute thing but if it doesn’t get merged I
don’t think it would bad, I’ll be posting a small PR for a loading state
for the form tonight. It has a slight awkward lag.

**Comment by fvcproductions** [comment]
Current in the process of adding my intro as a maker - I believe you might be prompted to do this as well @benjaminmodayil

**Comment by benjaminmodayil** [comment]
@fvcproductions I'll be on the lookout. I haven't seen anything yet.

**Comment by fvcproductions** [comment]
@benjaminmodayil It's time to share!!

**Comment by fvcproductions** [comment]
https://www.producthunt.com/posts/apprenticeships-me

**Comment by fvcproductions** [comment]
@benjaminmodayil Just sent u an invite via LinkedIn FYI since it was private

**Comment by benjaminmodayil** [comment]
@fvcproductions I got it! Woohoo!

**Comment by fvcproductions** [comment]
@benjaminmodayil looks like it got scheduled to launch tomorrow which is weird - so i changed it to launch today

**Comment by fvcproductions** [comment]
@benjaminmodayil not sure why but cant edit it so don't share!!

https://www.producthunt.com/posts/apprenticeships-me

**Comment by fvcproductions** [comment]
or if u did, it looks like people cant upvote; i will contact support tho

**Comment by fvcproductions** [comment]
@benjaminmodayil in the meantime, this looks like a good resource: https://blog.producthunt.com/how-to-launch-on-product-hunt-7c1843e06399

**Comment by benjaminmodayil** [comment]
Sorry for not being responsive. I was having issues at work. For me, the launch still seems to be tomorrow. I tried upvoting but it just went back down. Should we still share?

**Comment by fvcproductions** [comment]
@benjaminmodayil it just automatically set launch date to tomorrow even though i scheduled it for today. maybe u can try editing it from dashboard?

<img width="831" alt="Screen Shot 2019-05-01 at 11 19 11 AM" src="https://user-images.githubusercontent.com/4284691/57033886-f94fc600-6c02-11e9-813b-c9d4a13eac67.png">

**Comment by fvcproductions** [comment]
when i tried editing to launch now, it didn't update at all 🤷🏽‍♀️

worst case scenario, we can just share tomorrow

**Comment by benjaminmodayil** [comment]
I think that might be safest bet at the moment 😆 I can't find where to change the date...

**Comment by fvcproductions** [comment]
😂lol thats dumb it set it to tomorrow without telling me why though; even why i do try to make it launch today, it's like nope and makes it tomorrow

but i think it's okay - we'll stick with original launch plan tomorrow and in the meantime, i will add PH badge to website

**Comment by fvcproductions** [comment]
## Template

Hey folks :wave::skin-tone-4:

I launched my first product on Product Hunt and would love it if you could take a look and let me know what you think! :product-hunt:

Apprenticeships.me is a directory of apprenticeship opportunities in the tech industry. These apprenticeship programs offer folks who have the hunger and drive but don't have traditional backgrounds with the pedigree the opportunity to not just break into the tech industry but flourish. :seedling:

https://www.producthunt.com/posts/apprenticeships-me

**Comment by benjaminmodayil** [comment]
Well, it seems we're live! Haha, I thought it was going to be live at 12pm.

**Comment by fvcproductions** [comment]
@benjaminmodayil yep seems that way! going to start sharing now 😂

**Comment by benjaminmodayil** [comment]
Links so far:

- LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:6529723175020822529/
- Facebook: https://www.facebook.com/benjamin.modayil (not sure how to get the direct link)
- Snapchat: I guess there is no link that would work for this kind of thing.
- Instagram: https://www.instagram.com/modayilme/
- Twitter: https://twitter.com/modayilme/status/1123954439834996736
- Thinkful Slack: https://i.imgur.com/u5xNm98.png
- Work Slack: https://i.imgur.com/IbkMcO6.png
- LevelUpTutorials JobBoard channel: https://i.imgur.com/EjrbRs5.png
- Wes Bos General Slack

Sadly, the reddit group I'm in does not like promotion/advertisements.

**Comment by fvcproductions** [comment]
- [x] [Slack Workspace - Slack - #dhtml](https://slack-pde.slack.com/archives/C8EDS0NFL/p1556812759480200)
- [x] [Slack Workspace - Slack - #cust-acq-random](https://slack-pde.slack.com/archives/C8JE5GX46/p1556812690000300)
- [x] [Slack Workspace - Slack - #diversity-inclusion](https://slack-pde.slack.com/archives/C0KM5UGQY/p1556813490011500)
- [x] [Slack Workspace - Techqueria - #random](https://latinos.slack.com/archives/C0KQUT1NU/p1556812380068800)
- [x] [Slack Workspace - Early Women Techmakers - #general](https://earlywtm.slack.com/archives/C0R9DN4AD/p1556812444227900)
- [x] [Slack Workspace - Write/Speak/Code - #signal-boost](https://wsccommunity.slack.com/archives/C6TR01Q5P/p1556812510006300)
- [x] [Slack Workspace - Women Who Code - #general](https://wwcode.slack.com/archives/C1LP4CSQ1/p1556812585023100)
- [ ] [Hacker News](https://news.ycombinator.com/user?id=fvcproductions)
- [x] [LinkedIn](https://www.linkedin.com/in/fvcproductions/) - [Reshare](https://www.linkedin.com/feed/update/urn:li:activity:6529739637861163008/)
- [ ] [Twitter](https://twitter.com/fvcproductions)
- [ ] [Instagram](https://www.instagram.com/fvcproductions/)
- [ ] [Reddit](https://www.reddit.com/user/fvcproductions)
- [ ] [Facebook](https://www.facebook.com/fvcproductions2013)
- [ ] Short Blog Post - [Medium](https://medium.com/@fvcproductions), [LinkedIn Posts](https://www.linkedin.com/in/fvcproductions/), [Personal Website](https://www.fvcproductions.com/)

**Comment by fvcproductions** [comment]
@benjaminmodayil try https://www.reddit.com/r/SideProject/

**Comment by benjaminmodayil** [comment]
@fvcproductions I tried posting on there, but whenever I would try creating one it would force a weird modal on me to sign in when I was already signed in.

**Comment by benjaminmodayil** [comment]
@fvcproductions We should try to figure out a way to grab stats and feedback related to the launch today whether counting likes + shares or etc. Possibly having a mini-retrospective of sorts either on an issue thread or otherwise.

**Comment by benjaminmodayil** [comment]
Some algolia stats for last week:
https://i.imgur.com/tWrLfzc.png


This is the usual:
https://i.imgur.com/nncVRg2.png
